import Head from "next/head";

export default function PessoaUsuaria() {
  return (
    <>
      <Head>
        <title>Lacrei</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
     batata
     cenoura
      </main>
    </>
  )
}